language: bash
# command to install dependencies
os:
  - "windows"
  
env:
  - PATH=/c/Program Files (x86)/MeCab/bin:/c/Python37:/c/Python37/Scripts:$PATH MECABRC='/c/Program Files (x86)/MeCab/etc/mecabrc'
before_install:
    - chcp.com 65001
    - wget "https://drive.google.com/uc?export=download&id=1syeEVA_bTfNtUTEGH67xbqEPd8ZatpTX" -O mecab.zip
    - unzip mecab.zip
    - mv MeCab '/c/Program Files (x86)'
    - choco install python
    - python -m pip install --upgrade pip


install:
  - python -V
  - pip install pipenv
  - pipenv install mecab-python-windows
# command to run tests
script:
  - pipenv run python mecab.py
