language: bash
# command to install dependencies
os:
  - "windows"
install:
  - cinst python pip
  - pip install pipenv
  - pipenv install mecab-python-windows
# command to run tests
script:
  - echo Done!
