language: bash
# command to install dependencies
os:
  - "windows"
install:
  - python3 -V
  - choco upgrade chocolatey
  - cinst python
  - source ~/.bashrc

  - python3 -V
  - pip3 install pipenv
#  - pipenv install mecab-python-windows
# command to run tests
script:
  - echo Done!
