language: python
python:
  - "3.7"
# command to install dependencies
os:
  - "windows"
install:
  - pip install pipenv
  - pipenv install mecab-python-windows
# command to run tests
script:
  - echo Done!
