language: bash
# command to install dependencies
os:
  - "windows"
install:
  - cinst python
  - pip3 install pipenv
  - pipenv install mecab-python-windows
# command to run tests
script:
  - echo Done!
