language: bash
# command to install dependencies
os:
  - "windows"
install:
  - python -V
  - choco upgrade chocolatey
  - cinst python
  refreshenv
  - python -V
  - pip install pipenv
#  - pipenv install mecab-python-windows
# command to run tests
script:
  - echo Done!
